/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfilRouteImport } from './routes/_app/profil'
import { Route as AppPrecompteRouteImport } from './routes/_app/precompte'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConformiteTvaRouteImport } from './routes/_app/conformite-tva'
import { Route as AppVehiculesIndexRouteImport } from './routes/_app/vehicules.index'
import { Route as AppPersonnelIndexRouteImport } from './routes/_app/personnel.index'
import { Route as AppFacturationIndexRouteImport } from './routes/_app/facturation.index'
import { Route as AppChantiersIndexRouteImport } from './routes/_app/chantiers.index'
import { Route as AppVehiculesIdRouteImport } from './routes/_app/vehicules.$id'
import { Route as AppPersonnelIdRouteImport } from './routes/_app/personnel.$id'
import { Route as AppFacturationIdRouteImport } from './routes/_app/facturation.$id'
import { Route as AppChantiersIdRouteImport } from './routes/_app/chantiers.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppPrecompteRoute = AppPrecompteRouteImport.update({
  id: '/precompte',
  path: '/precompte',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConformiteTvaRoute = AppConformiteTvaRouteImport.update({
  id: '/conformite-tva',
  path: '/conformite-tva',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiculesIndexRoute = AppVehiculesIndexRouteImport.update({
  id: '/vehicules/',
  path: '/vehicules/',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonnelIndexRoute = AppPersonnelIndexRouteImport.update({
  id: '/personnel/',
  path: '/personnel/',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturationIndexRoute = AppFacturationIndexRouteImport.update({
  id: '/facturation/',
  path: '/facturation/',
  getParentRoute: () => AppRoute,
} as any)
const AppChantiersIndexRoute = AppChantiersIndexRouteImport.update({
  id: '/chantiers/',
  path: '/chantiers/',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiculesIdRoute = AppVehiculesIdRouteImport.update({
  id: '/vehicules/$id',
  path: '/vehicules/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonnelIdRoute = AppPersonnelIdRouteImport.update({
  id: '/personnel/$id',
  path: '/personnel/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturationIdRoute = AppFacturationIdRouteImport.update({
  id: '/facturation/$id',
  path: '/facturation/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChantiersIdRoute = AppChantiersIdRouteImport.update({
  id: '/chantiers/$id',
  path: '/chantiers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/conformite-tva': typeof AppConformiteTvaRoute
  '/dashboard': typeof AppDashboardRoute
  '/precompte': typeof AppPrecompteRoute
  '/profil': typeof AppProfilRoute
  '/chantiers/$id': typeof AppChantiersIdRoute
  '/facturation/$id': typeof AppFacturationIdRoute
  '/personnel/$id': typeof AppPersonnelIdRoute
  '/vehicules/$id': typeof AppVehiculesIdRoute
  '/chantiers/': typeof AppChantiersIndexRoute
  '/facturation/': typeof AppFacturationIndexRoute
  '/personnel/': typeof AppPersonnelIndexRoute
  '/vehicules/': typeof AppVehiculesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/conformite-tva': typeof AppConformiteTvaRoute
  '/dashboard': typeof AppDashboardRoute
  '/precompte': typeof AppPrecompteRoute
  '/profil': typeof AppProfilRoute
  '/chantiers/$id': typeof AppChantiersIdRoute
  '/facturation/$id': typeof AppFacturationIdRoute
  '/personnel/$id': typeof AppPersonnelIdRoute
  '/vehicules/$id': typeof AppVehiculesIdRoute
  '/chantiers': typeof AppChantiersIndexRoute
  '/facturation': typeof AppFacturationIndexRoute
  '/personnel': typeof AppPersonnelIndexRoute
  '/vehicules': typeof AppVehiculesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/conformite-tva': typeof AppConformiteTvaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/precompte': typeof AppPrecompteRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/chantiers/$id': typeof AppChantiersIdRoute
  '/_app/facturation/$id': typeof AppFacturationIdRoute
  '/_app/personnel/$id': typeof AppPersonnelIdRoute
  '/_app/vehicules/$id': typeof AppVehiculesIdRoute
  '/_app/chantiers/': typeof AppChantiersIndexRoute
  '/_app/facturation/': typeof AppFacturationIndexRoute
  '/_app/personnel/': typeof AppPersonnelIndexRoute
  '/_app/vehicules/': typeof AppVehiculesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/conformite-tva'
    | '/dashboard'
    | '/precompte'
    | '/profil'
    | '/chantiers/$id'
    | '/facturation/$id'
    | '/personnel/$id'
    | '/vehicules/$id'
    | '/chantiers/'
    | '/facturation/'
    | '/personnel/'
    | '/vehicules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/conformite-tva'
    | '/dashboard'
    | '/precompte'
    | '/profil'
    | '/chantiers/$id'
    | '/facturation/$id'
    | '/personnel/$id'
    | '/vehicules/$id'
    | '/chantiers'
    | '/facturation'
    | '/personnel'
    | '/vehicules'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/conformite-tva'
    | '/_app/dashboard'
    | '/_app/precompte'
    | '/_app/profil'
    | '/_app/chantiers/$id'
    | '/_app/facturation/$id'
    | '/_app/personnel/$id'
    | '/_app/vehicules/$id'
    | '/_app/chantiers/'
    | '/_app/facturation/'
    | '/_app/personnel/'
    | '/_app/vehicules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/precompte': {
      id: '/_app/precompte'
      path: '/precompte'
      fullPath: '/precompte'
      preLoaderRoute: typeof AppPrecompteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conformite-tva': {
      id: '/_app/conformite-tva'
      path: '/conformite-tva'
      fullPath: '/conformite-tva'
      preLoaderRoute: typeof AppConformiteTvaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicules/': {
      id: '/_app/vehicules/'
      path: '/vehicules'
      fullPath: '/vehicules/'
      preLoaderRoute: typeof AppVehiculesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personnel/': {
      id: '/_app/personnel/'
      path: '/personnel'
      fullPath: '/personnel/'
      preLoaderRoute: typeof AppPersonnelIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facturation/': {
      id: '/_app/facturation/'
      path: '/facturation'
      fullPath: '/facturation/'
      preLoaderRoute: typeof AppFacturationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chantiers/': {
      id: '/_app/chantiers/'
      path: '/chantiers'
      fullPath: '/chantiers/'
      preLoaderRoute: typeof AppChantiersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicules/$id': {
      id: '/_app/vehicules/$id'
      path: '/vehicules/$id'
      fullPath: '/vehicules/$id'
      preLoaderRoute: typeof AppVehiculesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personnel/$id': {
      id: '/_app/personnel/$id'
      path: '/personnel/$id'
      fullPath: '/personnel/$id'
      preLoaderRoute: typeof AppPersonnelIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facturation/$id': {
      id: '/_app/facturation/$id'
      path: '/facturation/$id'
      fullPath: '/facturation/$id'
      preLoaderRoute: typeof AppFacturationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chantiers/$id': {
      id: '/_app/chantiers/$id'
      path: '/chantiers/$id'
      fullPath: '/chantiers/$id'
      preLoaderRoute: typeof AppChantiersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConformiteTvaRoute: typeof AppConformiteTvaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPrecompteRoute: typeof AppPrecompteRoute
  AppProfilRoute: typeof AppProfilRoute
  AppChantiersIdRoute: typeof AppChantiersIdRoute
  AppFacturationIdRoute: typeof AppFacturationIdRoute
  AppPersonnelIdRoute: typeof AppPersonnelIdRoute
  AppVehiculesIdRoute: typeof AppVehiculesIdRoute
  AppChantiersIndexRoute: typeof AppChantiersIndexRoute
  AppFacturationIndexRoute: typeof AppFacturationIndexRoute
  AppPersonnelIndexRoute: typeof AppPersonnelIndexRoute
  AppVehiculesIndexRoute: typeof AppVehiculesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConformiteTvaRoute: AppConformiteTvaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPrecompteRoute: AppPrecompteRoute,
  AppProfilRoute: AppProfilRoute,
  AppChantiersIdRoute: AppChantiersIdRoute,
  AppFacturationIdRoute: AppFacturationIdRoute,
  AppPersonnelIdRoute: AppPersonnelIdRoute,
  AppVehiculesIdRoute: AppVehiculesIdRoute,
  AppChantiersIndexRoute: AppChantiersIndexRoute,
  AppFacturationIndexRoute: AppFacturationIndexRoute,
  AppPersonnelIndexRoute: AppPersonnelIndexRoute,
  AppVehiculesIndexRoute: AppVehiculesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
